import "dotenv/config";
import { Worker } from "bullmq";
import { Prisma } from "@prisma/client";
import { prisma } from "../../src/lib/db";
import { generateAssessmentReport } from "../../src/lib/report-generator";
import { assessmentQueueName, getBullConnectionOptions } from "../../src/lib/queue";
import type { ScoredProfile } from "../../src/lib/contracts";
import { parseLocale, type Locale } from "../../src/lib/locale";

type AssessmentJobData = {
  sessionId: string;
  reportJobId: string;
  locale?: string;
};

async function log(jobId: string, stage: string, message: string, metadata?: Record<string, unknown>) {
  await prisma.agentLog.create({
    data: { jobId, stage, message, metadata: metadata as Prisma.InputJsonValue | undefined }
  });
}

async function updateJob(jobId: string, stage: string, progress: number) {
  await prisma.reportJob.update({
    where: { id: jobId },
    data: { stage, progress, status: "RUNNING", startedAt: new Date() }
  });
}

function workerMessage(locale: Locale, key: "mapping" | "plan" | "safety" | "publish") {
  const messages = {
    en: {
      mapping: "Loaded deterministic profile and normalized health signals.",
      plan: "Generated a four-week Pilates plan from structured constraints.",
      safety: "Checked plan language for unsafe claims and contraindication handling.",
      publish: "Published preview and entitlement-gated full plan."
    },
    zh: {
      mapping: "已读取稳定评分画像，并整理健康信号。",
      plan: "已根据你的节奏和安全边界生成 4 周普拉提计划。",
      safety: "已检查计划文案，避免医疗化承诺和不合适的动作建议。",
      publish: "已生成预览，并准备好订阅后解锁的完整计划。"
    }
  };

  return messages[locale][key];
}

const worker = new Worker<AssessmentJobData>(
  assessmentQueueName,
  async (bullJob) => {
    const { sessionId, reportJobId } = bullJob.data;
    const locale = parseLocale(bullJob.data.locale);

    try {
      await updateJob(reportJobId, "mapping_signals", 15);
      await log(reportJobId, "mapping_signals", workerMessage(locale, "mapping"));

      const session = await prisma.assessmentSession.findUnique({
        where: { id: sessionId },
        include: { profile: true }
      });

      if (!session?.profile) {
        throw new Error("Assessment profile is missing; complete scoring before report generation.");
      }

      const profile: ScoredProfile = {
        signals: session.profile.signals as ScoredProfile["signals"],
        scores: session.profile.scores as ScoredProfile["scores"],
        riskFlags: session.profile.riskFlags as ScoredProfile["riskFlags"],
        planConstraints: session.profile.planConstraints as ScoredProfile["planConstraints"],
        preview: session.profile.preview as ScoredProfile["preview"],
        healthMetrics: (session.profile.healthMetrics as ScoredProfile["healthMetrics"]) ?? null
      };

      await prisma.reportArtifact.create({
        data: {
          jobId: reportJobId,
          type: "health-profile",
          version: 1,
          payload: profile
        }
      });

      await updateJob(reportJobId, "building_plan", 45);
      await log(reportJobId, "building_plan", workerMessage(locale, "plan"));
      const report = await generateAssessmentReport(profile, locale);

      await updateJob(reportJobId, "safety_review", 72);
      await log(reportJobId, "safety_review", workerMessage(locale, "safety"));

      // Persist the writer/reviewer reflection loop as an auditable trace.
      for (const step of report.trace) {
        await log(reportJobId, `agent_${step.agent}`, `${step.agent}: ${step.status}${step.detail ? ` - ${step.detail}` : ""}`, {
          agent: step.agent,
          status: step.status,
          detail: step.detail
        });
      }
      await log(
        reportJobId,
        "safety_review",
        report.generatedBy === "ai"
          ? locale === "zh"
            ? "计划文案由 AI 生成并通过独立安全审查。"
            : "Plan narrative generated by AI and passed independent safety review."
          : locale === "zh"
            ? "使用确定性兜底文案（未启用 AI、调用失败或未通过安全审查）。"
            : "Used deterministic fallback narrative (AI disabled, failed, or not approved).",
        { generatedBy: report.generatedBy }
      );

      await prisma.reportArtifact.create({
        data: {
          jobId: reportJobId,
          type: "generation-trace",
          version: 1,
          payload: { generatedBy: report.generatedBy, steps: report.trace }
        }
      });

      await prisma.reportArtifact.createMany({
        data: [
          {
            jobId: reportJobId,
            type: "workout-plan",
            version: 1,
            payload: report.fullPlan
          },
          {
            jobId: reportJobId,
            type: "safety-review",
            version: 1,
            payload: report.safety
          }
        ]
      });

      await updateJob(reportJobId, "publishing", 90);
      await log(reportJobId, "publishing", workerMessage(locale, "publish"));

      await prisma.assessmentResult.create({
        data: {
          sessionId,
          reportJobId,
          previewPayload: report.preview,
          fullPayload: report.fullPlan,
          safetyPayload: report.safety
        }
      });

      await prisma.reportJob.update({
        where: { id: reportJobId },
        data: {
          status: "SUCCEEDED",
          progress: 100,
          stage: "ready",
          finishedAt: new Date()
        }
      });
    } catch (error) {
      await prisma.reportJob.update({
        where: { id: reportJobId },
        data: {
          status: "FAILED",
          stage: "failed",
          error: error instanceof Error ? error.message : "Unknown worker error",
          finishedAt: new Date()
        }
      });
      throw error;
    }
  },
  { connection: getBullConnectionOptions() }
);

worker.on("completed", (job) => {
  console.log(`Assessment job ${job.id} completed`);
});

worker.on("failed", (job, error) => {
  console.error(`Assessment job ${job?.id} failed`, error);
});

console.log(`Worker listening on ${assessmentQueueName}`);
